### ISSUE TITLE
LCD LASCAR DDM4

### ISSUE THREAD

**Issue by Ivra23** [supercrab/arduino-seven-segment#3]
Hello,
Thank you for your library which is very interesting and helps a lot of people.
I have LCD LASCAR DDM4, I connected CK, DI and LOAD, to pin 3,4 and 5 and DEGREES, COLON and POINT to BP for now. but I can not operate the LCD, they show me weird characters.
You can help me? 
Thank you so much,

**Comment by Ivra23** [comment]
Hello,
If i write 5 i have 2 in the right and if i write 2 i have H, 0 i have 9.
I don't know why ? I just use Basic example.

```
#include <SevenSegment.h>

#define CLOCK 3 // Arudino digital 3-> AY0438 clock
#define DATA  4	 // Arudino digital 4 -> AY0438 data
#define LOAD  5  // Arudino digital 5 -> AY0438 load

SevenSegment screen(CLOCK, DATA, LOAD);

void setup(){
	// Set display driver AY0438 and screen definition
	screen.begin("AY0438","8");
}

void loop(){

screen.printNumber(5);
delay(200);

}
```

**Comment by supercrab** [comment]
Hi I think you have wired up your segments incorrectly. You have to wire
segment A, then B , etc

**Comment by supercrab** [comment]
Hi

Thanks for your kind words!

I’ve looked at the spec sheet for your LCD screen and it looks like my
library won’t work for your display :(

The mechanism for communicating is the controller is directly wired to the
screen nd expects the data in a certain order.  The library would need to
be rewritten.

Thanks
Mase

**Comment by Ivra23** [comment]
Hello,
Thank you for your answer, How can I rewrite the library with taking your example. 
You can just explain to me ?. Thank you

**Comment by supercrab** [comment]
It looks like supporting your display is outside the scope of the library :(
